import math

# Игровые настройки
FPS = 60
TILE_SIZE = 100
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
HALF_WINDOW_WIDTH = WINDOW_WIDTH // 2
HALF_WINDOW_HEIGHT = WINDOW_HEIGHT // 2

# Игровые цвета
WHITE = (255,255,255)
BLACK = (0,0,0)
RED = (255,0,0)
GREEN = (0,255,0)
BLUE = (0,0,255)
DARKGRAY = (100,100,100)
PURPLE = (120,0,120)

# Настройки игрока
PLAYER_POS = (HALF_WINDOW_WIDTH, HALF_WINDOW_HEIGHT)
PLAYER_ANGLE = 0
PLAYER_SPEED= 2

# Параметры излучения "взгляда"
FOV = math.pi / 3
HALF_FOV = FOV / 2
RAY_AMOUNT = 220
MAX_DEPTH_OF_VIEW = 800
DELTA_OF_ANGLE = FOV / RAY_AMOUNT
DISTANCE = RAY_AMOUNT / (math.tan(HALF_FOV) * 2)
PROJECTION_COEFFICIENT = DISTANCE * TILE_SIZE
SCALE_OF_VIEW = WINDOW_WIDTH // RAY_AMOUNT