import math

# Игровые настройки
TILE_SIZE = 100
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
HALF_WINDOW_WIDTH = WINDOW_WIDTH // 2
HALF_WINDOW_HEIGHT = WINDOW_HEIGHT // 2
FPS = 60
FPS_COORDINATES = (WINDOW_WIDTH - 50, 5)

#
MINIMAP_SCALE = 5
MINIMAP_TILE = TILE_SIZE // MINIMAP_SCALE
MINIMAP_COORDINATES = (0, WINDOW_HEIGHT - WINDOW_HEIGHT // MINIMAP_SCALE)

#
TEXTURE_WIDTH = 1000
TEXTURE_HEIGHT = 1000
TEXTURE_SCALE = TEXTURE_WIDTH // TILE_SIZE

# Игровые цвета
WHITE = (255,255,255)
BLACK = (0,0,0)
RED = (255,0,0)
GREEN = (0,80,0)
BLUE = (0,0,255)
YELLOW = (220,220,0)
DARKGRAY = (100,100,100)
PURPLE = (120,0,120)
SKYBLUE = (0, 186, 255)

# Настройки игрока
PLAYER_POS = (HALF_WINDOW_WIDTH, HALF_WINDOW_HEIGHT)
PLAYER_ANGLE = 0
PLAYER_SPEED= 2

# Параметры излучения "взгляда"
FOV = math.pi / 3
HALF_FOV = FOV / 2
RAY_AMOUNT = 300
MAX_DEPTH_OF_VIEW = 800
DELTA_OF_ANGLE = FOV / RAY_AMOUNT
DISTANCE = RAY_AMOUNT / (math.tan(HALF_FOV) * 2)
PROJECTION_COEFFICIENT = 3* DISTANCE * TILE_SIZE
SCALE_OF_VIEW = WINDOW_WIDTH // RAY_AMOUNT